### ISSUE TITLE
When will this be available on looker studio?

### ISSUE THREAD

**Issue by d-meehan** [Gladior-B-V/tiktok-connector#1]
Apologies if I've missed it somewhere, but I can't find this connector on looker studio or anything online about when it might be available.

**Comment by gladior-wouter** [comment]
Hi @d-meehan,

Thank you for reaching out. Unfortunately, our TikTok connector is still under review by Google and has not yet been published in the Connector Gallery. In the meantime, you can use our TikTok connector via [this link](https://lookerstudio.google.com/datasources/create?connectorId=AKfycbz72u7FgG48z0ukcp6z_mGwwD3DU1jJjCdbQU960qWeWvr-WKrEAQoiOxFEo0wtp8Ho), however. If you encounter any issues or have further questions, please let us know.

Best regards,

Wouter | Gladior

**Comment by d-meehan** [comment]
This is great, thanks so much (and thanks for your work on connectors generally). Does this only work to connect to TikTok social accounts, or can it link to ads accounts?

**Comment by gladior-wouter** [comment]
Thank you for the kind words, @d-meehan! At the moment, our connector only supports insights on account and video data for TikTok (business) accounts. We would like to expand our connector to include ads insights in the future, but we do not have an estimated timeline currently. However, if you require this functionality sooner, we can develop it as a paid service. Please let us know if you're interested!
